# Generated by Django 3.0 on 2019-12-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_ID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=250)),
                ('client_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('model_number', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('cell_technology', models.CharField(max_length=250)),
                ('cell_manufacturer', models.CharField(max_length=250)),
                ('number_of_cells', models.CharField(max_length=250)),
                ('number_of_cells_in_series', models.CharField(max_length=250)),
                ('number_of_series_strings', models.CharField(max_length=250)),
                ('number_of_diodes', models.CharField(max_length=250)),
                ('product_length', models.CharField(max_length=250)),
                ('product_width', models.CharField(max_length=250)),
                ('product_weight', models.CharField(max_length=250)),
                ('superstate_type', models.CharField(max_length=250)),
                ('superstate_manufacturer', models.CharField(max_length=250)),
                ('substrate_type', models.CharField(max_length=250)),
                ('substrate_manufacturer', models.CharField(max_length=250)),
                ('frame_type', models.CharField(max_length=250)),
                ('frame_adhesive', models.CharField(max_length=250)),
                ('encapsulate_type', models.CharField(max_length=250)),
                ('encapsulate_manufacturer', models.CharField(max_length=250)),
                ('junction_box_type', models.CharField(max_length=250)),
                ('junction_box_manufacturer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('userID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=250)),
                ('middlename', models.CharField(blank=True, max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('zipcode', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('officephone', models.CharField(blank=True, max_length=250)),
                ('cellphone', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Sequence',
            fields=[
                ('sequence_ID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('sequence_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Standard',
            fields=[
                ('standard_ID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('standard_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('published_date', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('job_title', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('office_phone', models.CharField(max_length=250)),
                ('cell_phone', models.CharField(max_length=250)),
                ('prefix', models.CharField(max_length=250)),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_ID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('is_FI_required', models.CharField(max_length=250)),
                ('FI_frequency', models.CharField(max_length=250)),
                ('standard_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Test_Standard')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_ID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('fax_number', models.CharField(max_length=250)),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_number', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('ID', models.CharField(max_length=250)),
                ('report_number', models.CharField(max_length=250)),
                ('issue_date', models.CharField(max_length=250)),
                ('location_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Location')),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Product')),
                ('standard_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Test_Standard')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.User')),
            ],
        ),
        migrations.CreateModel(
            name='Performance_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_system_voltage', models.CharField(max_length=250)),
                ('voc', models.CharField(max_length=250)),
                ('isc', models.CharField(max_length=250)),
                ('vmp', models.CharField(max_length=250)),
                ('imp', models.CharField(max_length=250)),
                ('pmp', models.CharField(max_length=250)),
                ('ff', models.CharField(max_length=250)),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Product')),
                ('sequence_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Test_Sequence')),
            ],
            options={
                'unique_together': {('model_number', 'sequence_ID')},
            },
        ),
    ]
